export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_LIST_FILTER = "PRODUCT_LIST_FILTER";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
